export const actions = {
	CHECK_LOCAL_STORAGE: 'CHECK_LOCAL_STORAGE',
	LOGIN: 'LOGIN',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	REQUEST_DATA: 'REQUEST_DATA',
	DATA_RECEIVED: 'DATA_RECEIVED',
	CLEAR_DATA: 'CLEAR_DATA',
	SET_COUNTRY_FILTER: 'SET_COUNTRY_FILTER',
	SET_DISTANCE_FILTER: 'SET_DISTANCE_FILTER',
	RESET_FILTER: 'RESET_FILTER',
	LOGOUT: 'LOGOUT',
	SET_USERNAME: 'SET_USERNAME',
	SET_PASSWORD: 'SET_PASSWORD',
};
